name: schedule-test

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "Scheduled run works!"
          date -u
